name: Security CI

on:
  push:
    branches: [main, master, develop]
  pull_request:
    branches: [main, master, develop]

jobs:
  security:
    name: Android Security
    uses: thiagoolima99/repo-central/.github/workflows/reusable-android-security.yml@main
    with:
      fail-on-high: true
    secrets: inherit
    permissions:
      contents: read
